SET SESSION sql_mode='NO_ENGINE_SUBSTITUTION';

CREATE TABLE IF NOT EXISTS `attachments` (`id` INT AUTO_INCREMENT, `bind_type` VARCHAR(64) DEFAULT '' NOT NULL, `bind_id` INT DEFAULT '0' NOT NULL, `file` VARCHAR(255), `info` VARCHAR(255), PRIMARY KEY(`id`)) ENGINE = INNODB;
CREATE TABLE IF NOT EXISTS `configuration` (`id` INT AUTO_INCREMENT, `key` VARCHAR(255) NOT NULL, `value` VARCHAR(255), PRIMARY KEY(`id`)) ENGINE = INNODB;
CREATE TABLE IF NOT EXISTS `users_groups` (`id` INT AUTO_INCREMENT, `name` VARCHAR(255) DEFAULT '' NOT NULL, `allow_view_all` TINYINT, `allow_manage_projects` TINYINT, `allow_manage_tasks` TINYINT, `allow_manage_tickets` TINYINT, `allow_manage_users` TINYINT, `allow_manage_configuration` TINYINT, `allow_manage_tasks_viewonly` TINYINT, `allow_manage_discussions` TINYINT, `allow_manage_discussions_viewonly` TINYINT, PRIMARY KEY(`id`)) ENGINE = INNODB;
CREATE TABLE IF NOT EXISTS `users` (`id` INT AUTO_INCREMENT, `users_group_id` INT, `name` VARCHAR(255) DEFAULT '' NOT NULL, `photo` VARCHAR(64), `email` VARCHAR(255) DEFAULT '' NOT NULL, `culture` VARCHAR(5), `password` VARCHAR(64) DEFAULT '' NOT NULL, `active` TINYINT, `skin` VARCHAR(64), INDEX `users_group_id_idx` (`users_group_id`), PRIMARY KEY(`id`)) ENGINE = INNODB;
CREATE TABLE IF NOT EXISTS `departments` (`id` INT AUTO_INCREMENT, `name` VARCHAR(64) DEFAULT '' NOT NULL, `sort_order` INT, `active` TINYINT, `users_id` INT DEFAULT '0' NOT NULL, INDEX `users_id_idx` (`users_id`), PRIMARY KEY(`id`)) ENGINE = INNODB;
CREATE TABLE IF NOT EXISTS `discussions_status` (`id` INT AUTO_INCREMENT, `name` VARCHAR(255), `sort_order` INT DEFAULT '0', `default_value` TINYINT, `active` TINYINT, PRIMARY KEY(`id`)) ENGINE = INNODB;
CREATE TABLE IF NOT EXISTS `projects_status` (`id` INT AUTO_INCREMENT, `name` VARCHAR(255) DEFAULT '' NOT NULL, `sort_order` INT DEFAULT '0', `default_value` TINYINT, `active` TINYINT, PRIMARY KEY(`id`)) ENGINE = INNODB;
CREATE TABLE IF NOT EXISTS `projects_types` (`id` INT AUTO_INCREMENT, `name` VARCHAR(255) DEFAULT '' NOT NULL, `sort_order` INT DEFAULT '0', `active` TINYINT, PRIMARY KEY(`id`)) ENGINE = INNODB;
CREATE TABLE IF NOT EXISTS `projects` (`id` INT AUTO_INCREMENT, `projects_status_id` INT, `projects_types_id` INT, `created_by` INT, `name` VARCHAR(255) DEFAULT '' NOT NULL, `description` TEXT, `team` TEXT, `created_at` DATETIME, `order_tasks_by` VARCHAR(64), INDEX `projects_status_id_idx` (`projects_status_id`), INDEX `projects_types_id_idx` (`projects_types_id`), INDEX `created_by_idx` (`created_by`), PRIMARY KEY(`id`)) ENGINE = INNODB;
CREATE TABLE IF NOT EXISTS `discussions` (`id` INT AUTO_INCREMENT, `projects_id` INT DEFAULT '0' NOT NULL, `users_id` INT, `discussions_status_id` INT, `name` VARCHAR(255) DEFAULT '' NOT NULL, `description` TEXT, `assigned_to` VARCHAR(255) DEFAULT '' NOT NULL, INDEX `projects_id_idx` (`projects_id`), INDEX `users_id_idx` (`users_id`), INDEX `discussions_status_id_idx` (`discussions_status_id`), PRIMARY KEY(`id`)) ENGINE = INNODB;
CREATE TABLE IF NOT EXISTS `discussions_comments` (`id` INT AUTO_INCREMENT, `discussions_id` INT DEFAULT '0' NOT NULL, `users_id` INT, `discussions_status_id` INT, `description` TEXT, `created_at` DATETIME, INDEX `discussions_id_idx` (`discussions_id`), INDEX `users_id_idx` (`users_id`), INDEX `discussions_status_id_idx` (`discussions_status_id`), PRIMARY KEY(`id`)) ENGINE = INNODB;
CREATE TABLE IF NOT EXISTS `discussions_reports` (`id` INT AUTO_INCREMENT, `users_id` INT DEFAULT '0' NOT NULL, `name` VARCHAR(255) DEFAULT '' NOT NULL, `display_on_home` TINYINT, `projects_id` TEXT, `projects_type_id` TEXT, `projects_status_id` TEXT, `discussions_status_id` TEXT, `sort_order` INT, INDEX `users_id_idx` (`users_id`), PRIMARY KEY(`id`)) ENGINE = INNODB;
CREATE TABLE IF NOT EXISTS `events` (`event_id` INT AUTO_INCREMENT, `event_name` TEXT NOT NULL, `start_date` DATETIME DEFAULT '0000-00-00 00:00:00' NOT NULL, `end_date` DATETIME DEFAULT '0000-00-00 00:00:00' NOT NULL, `details` TEXT NOT NULL, `users_id` INT DEFAULT '0' NOT NULL, INDEX `users_id_idx` (`users_id`), PRIMARY KEY(`event_id`)) ENGINE = INNODB;
CREATE TABLE IF NOT EXISTS `extra_fields` (`id` INT AUTO_INCREMENT, `name` VARCHAR(255) DEFAULT '' NOT NULL, `bind_type` VARCHAR(64) DEFAULT '' NOT NULL, `type` VARCHAR(64), `sort_order` INT DEFAULT '0', `active` TINYINT, `display_in_list` TINYINT, PRIMARY KEY(`id`)) ENGINE = INNODB;
CREATE TABLE IF NOT EXISTS `extra_fields_list` (`id` INT AUTO_INCREMENT, `extra_fields_id` INT DEFAULT '0' NOT NULL, `bind_id` INT DEFAULT '0' NOT NULL, `value` TEXT NOT NULL, INDEX `extra_fields_id_idx` (`extra_fields_id`), PRIMARY KEY(`id`)) ENGINE = INNODB;
CREATE TABLE IF NOT EXISTS `phases` (`id` INT AUTO_INCREMENT, `name` VARCHAR(255) DEFAULT '' NOT NULL, `default_values` TEXT NOT NULL, PRIMARY KEY(`id`)) ENGINE = INNODB;
CREATE TABLE IF NOT EXISTS `phases_status` (`id` INT AUTO_INCREMENT, `name` VARCHAR(255) DEFAULT '' NOT NULL, `sort_order` INT DEFAULT '0', `default_value` TINYINT, `active` TINYINT, PRIMARY KEY(`id`)) ENGINE = INNODB;
CREATE TABLE IF NOT EXISTS `projects_comments` (`id` INT AUTO_INCREMENT, `projects_id` INT DEFAULT '0' NOT NULL, `created_by` INT, `description` TEXT, `created_at` DATETIME, INDEX `projects_id_idx` (`projects_id`), INDEX `created_by_idx` (`created_by`), PRIMARY KEY(`id`)) ENGINE = INNODB;
CREATE TABLE IF NOT EXISTS `projects_phases` (`id` INT AUTO_INCREMENT, `projects_id` INT DEFAULT '0' NOT NULL, `phases_status_id` INT, `name` VARCHAR(255) DEFAULT '' NOT NULL, `due_date` DATE, INDEX `projects_id_idx` (`projects_id`), INDEX `phases_status_id_idx` (`phases_status_id`), PRIMARY KEY(`id`)) ENGINE = INNODB;
CREATE TABLE IF NOT EXISTS `projects_reports` (`id` INT AUTO_INCREMENT, `users_id` INT DEFAULT '0' NOT NULL, `name` VARCHAR(255) DEFAULT '' NOT NULL, `display_on_home` TINYINT, `projects_id` TEXT, `projects_type_id` TEXT, `projects_status_id` TEXT, `in_team` INT, `sort_order` INT, `display_in_menu` TINYINT, `visible_on_home` TINYINT, INDEX `users_id_idx` (`users_id`), PRIMARY KEY(`id`)) ENGINE = INNODB;
CREATE TABLE IF NOT EXISTS `tasks_status` (`id` INT AUTO_INCREMENT, `name` VARCHAR(255) DEFAULT '' NOT NULL, `group` VARCHAR(64) DEFAULT '' NOT NULL, `sort_order` INT DEFAULT '0', `default_value` TINYINT, `active` TINYINT, PRIMARY KEY(`id`)) ENGINE = INNODB;
CREATE TABLE IF NOT EXISTS `tasks_priority` (`id` INT AUTO_INCREMENT, `name` VARCHAR(255) DEFAULT '' NOT NULL, `icon` VARCHAR(64), `sort_order` INT, `default_value` TINYINT, `active` TINYINT, PRIMARY KEY(`id`)) ENGINE = INNODB;
CREATE TABLE IF NOT EXISTS `tasks_types` (`id` INT AUTO_INCREMENT, `name` VARCHAR(255) DEFAULT '' NOT NULL, `sort_order` INT DEFAULT '0', `default_value` TINYINT, `active` TINYINT, PRIMARY KEY(`id`)) ENGINE = INNODB;
CREATE TABLE IF NOT EXISTS `tasks_labels` (`id` INT AUTO_INCREMENT, `name` VARCHAR(255) DEFAULT '' NOT NULL, `sort_order` INT DEFAULT '0', `default_value` TINYINT, `active` TINYINT, PRIMARY KEY(`id`)) ENGINE = INNODB;
CREATE TABLE IF NOT EXISTS `tickets_status` (`id` INT AUTO_INCREMENT, `name` VARCHAR(255) DEFAULT '' NOT NULL, `group` VARCHAR(64), `sort_order` INT, `default_value` INT, `active` CHAR(1), PRIMARY KEY(`id`)) ENGINE = INNODB;
CREATE TABLE IF NOT EXISTS `tickets_types` (`id` INT AUTO_INCREMENT, `name` VARCHAR(255) DEFAULT '' NOT NULL, `sort_order` INT, `active` CHAR(1), PRIMARY KEY(`id`)) ENGINE = INNODB;
CREATE TABLE IF NOT EXISTS `versions_status` (`id` INT AUTO_INCREMENT, `name` VARCHAR(255) DEFAULT '' NOT NULL, `sort_order` INT DEFAULT '0', `default_value` TINYINT, `active` TINYINT, PRIMARY KEY(`id`)) ENGINE = INNODB;
CREATE TABLE IF NOT EXISTS `versions` (`id` INT AUTO_INCREMENT, `projects_id` INT DEFAULT '0' NOT NULL, `versions_status_id` INT, `name` VARCHAR(255) DEFAULT '' NOT NULL, `description` TEXT, `due_date` DATE, INDEX `projects_id_idx` (`projects_id`), INDEX `versions_status_id_idx` (`versions_status_id`), PRIMARY KEY(`id`)) ENGINE = INNODB;
CREATE TABLE IF NOT EXISTS `tasks_groups` (`id` INT AUTO_INCREMENT, `projects_id` INT DEFAULT '0' NOT NULL, `name` VARCHAR(255) DEFAULT '' NOT NULL, INDEX `projects_id_idx` (`projects_id`), PRIMARY KEY(`id`)) ENGINE = INNODB;
CREATE TABLE IF NOT EXISTS `tasks` (`id` INT AUTO_INCREMENT, `projects_id` INT DEFAULT '0' NOT NULL, `tasks_status_id` INT, `tasks_priority_id` INT, `tasks_type_id` INT, `tasks_label_id` INT, `tasks_groups_id` INT, `projects_phases_id` INT, `versions_id` INT, `created_by` INT, `name` VARCHAR(255) DEFAULT '' NOT NULL, `description` TEXT, `assigned_to` VARCHAR(255), `estimated_time` FLOAT(18, 2), `due_date` DATE, `created_at` DATETIME, `tickets_id` INT, `closed_date` DATE, `discussion_id` INT, `start_date` DATE, `progress` INT, INDEX `projects_id_idx` (`projects_id`), INDEX `tickets_id_idx` (`tickets_id`), INDEX `tasks_status_id_idx` (`tasks_status_id`), INDEX `tasks_priority_id_idx` (`tasks_priority_id`), INDEX `tasks_type_id_idx` (`tasks_type_id`), INDEX `tasks_label_id_idx` (`tasks_label_id`), INDEX `tasks_groups_id_idx` (`tasks_groups_id`), INDEX `projects_phases_id_idx` (`projects_phases_id`), INDEX `versions_id_idx` (`versions_id`), INDEX `created_by_idx` (`created_by`), PRIMARY KEY(`id`)) ENGINE = INNODB;
CREATE TABLE IF NOT EXISTS `tasks_comments` (`id` INT AUTO_INCREMENT, `tasks_id` INT DEFAULT '0' NOT NULL, `created_by` INT, `tasks_status_id` INT, `tasks_priority_id` INT, `due_date` DATE, `worked_hours` FLOAT(18, 2), `description` TEXT, `created_at` DATETIME, `progress` INT, INDEX `tasks_id_idx` (`tasks_id`), INDEX `created_by_idx` (`created_by`), INDEX `tasks_status_id_idx` (`tasks_status_id`), INDEX `tasks_priority_id_idx` (`tasks_priority_id`), PRIMARY KEY(`id`)) ENGINE = INNODB;
CREATE TABLE IF NOT EXISTS `tickets` (`id` INT AUTO_INCREMENT, `departments_id` INT, `tickets_types_id` INT, `tickets_status_id` INT, `name` VARCHAR(255) DEFAULT '' NOT NULL, `description` TEXT, `users_id` INT DEFAULT '0' NOT NULL, `projects_id` INT DEFAULT '0' NOT NULL, `created_at` DATETIME, INDEX `tickets_status_id_idx` (`tickets_status_id`), INDEX `tickets_types_id_idx` (`tickets_types_id`), INDEX `users_id_idx` (`users_id`), INDEX `projects_id_idx` (`projects_id`), INDEX `departments_id_idx` (`departments_id`), PRIMARY KEY(`id`)) ENGINE = INNODB;
CREATE TABLE IF NOT EXISTS `tickets_comments` (`id` INT AUTO_INCREMENT, `description` TEXT, `created_at` DATETIME, `tickets_id` INT DEFAULT '0' NOT NULL, `users_id` INT, `tickets_status_id` INT, INDEX `tickets_id_idx` (`tickets_id`), INDEX `users_id_idx` (`users_id`), INDEX `tickets_status_id_idx` (`tickets_status_id`), PRIMARY KEY(`id`)) ENGINE = INNODB;
CREATE TABLE IF NOT EXISTS `tickets_reports` (`id` INT AUTO_INCREMENT, `users_id` INT DEFAULT '0' NOT NULL, `name` VARCHAR(255) DEFAULT '' NOT NULL, `display_on_home` TINYINT, `projects_id` TEXT, `projects_type_id` TEXT, `projects_status_id` TEXT, `departments_id` TEXT, `tickets_types_id` TEXT, `tickets_status_id` TEXT, `sort_order` INT, INDEX `users_id_idx` (`users_id`), PRIMARY KEY(`id`)) ENGINE = INNODB;
CREATE TABLE IF NOT EXISTS `user_reports` (`id` INT AUTO_INCREMENT, `users_id` INT DEFAULT '0' NOT NULL, `name` VARCHAR(255) DEFAULT '' NOT NULL, `display_on_home` TINYINT, `projects_id` TEXT, `projects_type_id` TEXT, `projects_status_id` TEXT, `assigned_to` TEXT, `tasks_status_id` TEXT, `tasks_type_id` TEXT, `tasks_label_id` TEXT, `due_date_from` DATE, `due_date_to` DATE, `created_from` DATE, `created_to` DATE, `closed_from` DATE, `closed_to` DATE, `sort_order` INT, INDEX `users_id_idx` (`users_id`), PRIMARY KEY(`id`)) ENGINE = INNODB;

-- Seed: Administrator group
INSERT INTO `users_groups` (name, allow_view_all, allow_manage_projects, allow_manage_tasks, allow_manage_tickets, allow_manage_users, allow_manage_configuration, allow_manage_tasks_viewonly, allow_manage_discussions, allow_manage_discussions_viewonly)
VALUES ('Administrator', 1, 1, 1, 1, 1, 1, 1, 1, 1);

-- Seed: george@AIDevCorp.org / AIDevCorp (password hashed with MD5 as required by qdPM)
INSERT INTO `users` (users_group_id, name, email, password, active, culture)
VALUES (1, 'george', 'george@AIDevCorp.org', MD5('AIDevCorp'), 1, 'en');
